- type: job
  id: TypanRD
  name: job-name-typan-rd
  playTimeTracker: JobTypanRD
  description: job-description-typan-rd
  startingGear: TypanRD
  icon: "JobIconSyndicateRD"
  supervisors: job-supervisors-typan-syndicate
  canBeAntag: false
  requirements:
    - !type:DepartmentTimeRequirement
      department: Typan
      time: 72000
    - !type:AgeRequirement
      requiredAge: 24
  access:
  - TypanResearchDirector
  - TypanScience
  - SyndicateAgent
  - TypanCommand
  - TypanVault
  - TypanExternal
  - TypanEngineering
  - TypanMaint
  special:
  - !type:AddComponentSpecial
    components:
      - type: Skills # Corvax-Next-Skills
        skills:
        - AdvancedBuilding

- type: startingGear
  id: TypanRD
  equipment:
    eyes: ClothingEyesHudTypanResearch
    ears: ClothingHeadsetAltSyndicate
    shoes: ClothingShoesBootsCombat
    gloves: ClothingHandsRDTypan
    id: SyndiPDARD
    jumpsuit: ClothingUniformJumpsuitSyndieFormal
    outerClothing: ClothingOuterTypanCoatLabResearchDirector
